In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

In [6]:
options=webdriver.ChromeOptions()
driver=webdriver.Chrome(options=options)

In [7]:
driver.get("https://www.myntra.com/")

In [8]:
search=driver.find_element(By.XPATH,".//input[@class='desktop-searchBar']")

In [9]:
search.send_keys('smart watches')

In [10]:
search.send_keys(Keys.ENTER)

In [11]:
brand=driver.find_elements(By.XPATH,".//h3[@class='product-brand']")
brands=[i.text for i in brand]
print(brands)
len(brands)

['Fire-Boltt', 'pebble', 'pebble', 'NOISE', 'boAt', 'pebble', 'Fire-Boltt', 'CMF by Nothing', 'Fire-Boltt', 'Fire-Boltt', 'pebble', 'pebble', 'boAt', 'Fire-Boltt', 'NOISE', 'boAt', 'NOISE', 'pebble', 'Fire-Boltt', 'pebble', 'boAt', 'pebble', 'Fire-Boltt', 'boAt', 'pebble', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'NOISE', 'Realme', 'NOISE', 'Fire-Boltt', 'boAt', 'Fastrack', 'boAt', 'NOISE', 'Fire-Boltt', 'boAt', 'NOISE', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'boAt', 'Timex', 'NOISE', 'Fire-Boltt', 'Cultsport', 'CMF by Nothing']

50

In [13]:
desc=driver.find_elements(By.XPATH,".//h4[@class='product-product']")
descs=[i.text for i in desc]
print(descs)
len(descs)

['Hurricane Smartwatch', 'Celia 1.32" Display SmartWatch', 'Women 1.27" Smart Watch', 'Fit Posh Smartwatch', 'Unisex Wave Genesis Smartwatch', 'Celia 1.32" Display SmartWatch', 'Supernova Bluetooth SmartWatch', 'Watch Pro', 'Rock AMOLED Display Smartwatch', 'Starlight Bluetooth Smartwatch', 'Cosmos Ultra 1.91" BT Calling Smartwatch', 'Women 1.27" Smart Watch', 'Ultima Prism Smart Watch', 'Cobra AMOLED Smart Watch', 'Fit Posh Smartwatch', 'Lunar Tigon Smartwatch', 'Mettle EliteEdition Smartwatch', 'Hive 1.39" Display Smart Watch', 'Hulk 1.78 inch Smartwatch', 'Pepe Jeans Edition Smartwatch', 'Unisex Ultima Prism Smartwatch', 'Cosmos Quest Smartwatch', 'Eclipse Luxe 1.43" Amoled', 'Lunar Fit Smart Watch', 'Cosmos Ultra 1.91" BT Calling Smartwatch', 'Aura BT Calling Smartwatch', 'ColorFit Icon 2 Smartwatch', 'Visionary TWS Smartwatch', 'Fit Posh Smartwatch', 'TechLife Watch S100', 'ColorFit Icon 2 Smartwatch', 'Eclipse Luxe 1.43" Amoled', 'Storm Plus AMOLED Smart Watch', 'Z1 with HD Display Smartwatch', 'Lunar Fit Smart Watch', 'ColorFit Pro 5 Smartwatch', 'Sphere Rugged Smartwatch', 'Unisex Wave Genesis Smartwatch', 'Fit Posh Smartwatch', 'Avalanche Luxury Smart Watch', 'ColorFit Pro 5 Smartwatch', 'Hulk 1.78 inch Smartwatch', 'Evolve 3 Smartwatch', 'Hurricane Smartwatch', 'Lunar Mirage Smartwatch', 'iConnect Gen+ Smart Watch', 'ColorFit Pro 5 Smartwatch', 'Crusader Amoled 1.43BT Calling', 'Ace X Luxe 1.96" Smart Watches', 'Watch Pro']

50

In [19]:
price=driver.find_elements(By.XPATH,".//div[@class='product-price']")
prices=[i.text for i in price]
print(prices)
len(prices)

['Rs. 1700Rs. 8999(Rs. 7299 OFF)', 'Rs. 2299Rs. 7499(Rs. 5200 OFF)', 'Rs. 2299Rs. 6999(Rs. 4700 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 1899Rs. 6499(Rs. 4600 OFF)', 'Rs. 7499', 'Rs. 1899Rs. 18999(Rs. 17100 OFF)', 'Rs. 3499Rs. 5999(Rs. 2500 OFF)', 'Rs. 3199Rs. 18999(Rs. 15800 OFF)', 'Rs. 1599Rs. 14999(Rs. 13400 OFF)', 'Rs. 1599Rs. 7499(Rs. 5900 OFF)', 'Rs. 2299Rs. 6999(Rs. 4700 OFF)', 'Rs. 2349Rs. 8999(Rs. 6650 OFF)', 'Rs. 1899Rs. 19999(Rs. 18100 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 4199Rs. 11999(Rs. 7800 OFF)', 'Rs. 2249Rs. 7999(Rs. 5750 OFF)', 'Rs. 1699Rs. 6499(Rs. 4800 OFF)', 'Rs. 1799Rs. 17999(Rs. 16200 OFF)', 'Rs. 1999Rs. 5999(Rs. 4000 OFF)', 'Rs. 2599Rs. 9499(Rs. 6900 OFF)', 'Rs. 2499Rs. 9999(Rs. 7500 OFF)', 'Rs. 1799Rs. 19999(Rs. 18200 OFF)', 'Rs. 2999Rs. 6990(Rs. 3991 OFF)', 'Rs. 1599Rs. 7499(Rs. 5900 OFF)', 'Rs. 1999Rs. 11999(Rs. 10000 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 2499Rs. 18499(Rs. 16000 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 2499Rs. 3999(Rs. 1500 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 1999Rs. 19999(Rs. 18000 OFF)', 'Rs. 1899Rs. 8999(Rs. 7100 OFF)', 'Rs. 1995Rs. 3995(Rs. 2000 OFF)', 'Rs. 2999Rs. 6990(Rs. 3991 OFF)', 'Rs. 3999Rs. 8999(Rs. 5000 OFF)', 'Rs. 1899Rs. 19999(Rs. 18100 OFF)', 'Rs. 1899Rs. 6499(Rs. 4600 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 2199Rs. 21000(Rs. 18801 OFF)', 'Rs. 3999Rs. 8999(Rs. 5000 OFF)', 'Rs. 1799Rs. 17999(Rs. 16200 OFF)', 'Rs. 2449Rs. 6999(Rs. 4550 OFF)', 'Rs. 1899Rs. 8999(Rs. 7100 OFF)', 'Rs. 1599Rs. 7999(Rs. 6400 OFF)', 'Rs. 2527Rs. 5495(54% OFF)', 'Rs. 3999Rs. 8999(Rs. 5000 OFF)', 'Rs. 1899Rs. 18999(Rs. 17100 OFF)', 'Rs. 3479Rs. 11999(71% OFF)', 'Rs. 3499Rs. 5999(Rs. 2500 OFF)']

50

In [15]:
df=pd.DataFrame(columns=["Brand","Desc","Price"])
df

Empty DataFrame
Columns: [Brand, Desc, Price]
Index: []

In [21]:
df['Brand']=brands
df['Desc']=descs
df['Price']=prices

In [24]:
df.to_csv("smart watches.csv")
df

,Brand,Desc,Price
0,Fire-Boltt,Hurricane Smartwatch,Rs. 1700Rs. 8999(Rs. 7299 OFF)
1,pebble,"Celia 1.32"" Display SmartWatch",Rs. 2299Rs. 7499(Rs. 5200 OFF)
2,pebble,"Women 1.27"" Smart Watch",Rs. 2299Rs. 6999(Rs. 4700 OFF)
3,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
4,boAt,Unisex Wave Genesis Smartwatch,Rs. 1899Rs. 6499(Rs. 4600 OFF)
5,pebble,"Celia 1.32"" Display SmartWatch",Rs. 7499
6,Fire-Boltt,Supernova Bluetooth SmartWatch,Rs. 1899Rs. 18999(Rs. 17100 OFF)
7,CMF by Nothing,Watch Pro,Rs. 3499Rs. 5999(Rs. 2500 OFF)
8,Fire-Boltt,Rock AMOLED Display Smartwatch,Rs. 3199Rs. 18999(Rs. 15800 OFF)
9,Fire-Boltt,Starlight Bluetooth Smartwatch,Rs. 1599Rs. 14999(Rs. 13400 OFF)
10,pebble,"Cosmos Ultra 1.91"" BT Calling Smartwatch",Rs. 1599Rs. 7499(Rs. 5900 OFF)
11,pebble,"Women 1.27"" Smart Watch",Rs. 2299Rs. 6999(Rs. 4700 OFF)
12,boAt,Ultima Prism Smart Watch,Rs. 2349Rs. 8999(Rs. 6650 OFF)
13,Fire-Boltt,Cobra AMOLED Smart Watch,Rs. 1899Rs. 19999(Rs. 18100 OFF)
14,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
15,boAt,Lunar Tigon Smartwatch,Rs. 4199Rs. 11999(Rs. 7800 OFF)
16,NOISE,Mettle EliteEdition Smartwatch,Rs. 2249Rs. 7999(Rs. 5750 OFF)
17,pebble,"Hive 1.39"" Display Smart Watch",Rs. 1699Rs. 6499(Rs. 4800 OFF)
18,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1799Rs. 17999(Rs. 16200 OFF)
19,pebble,Pepe Jeans Edition Smartwatch,Rs. 1999Rs. 5999(Rs. 4000 OFF)
20,boAt,Unisex Ultima Prism Smartwatch,Rs. 2599Rs. 9499(Rs. 6900 OFF)
21,pebble,Cosmos Quest Smartwatch,Rs. 2499Rs. 9999(Rs. 7500 OFF)
22,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1799Rs. 19999(Rs. 18200 OFF)
23,boAt,Lunar Fit Smart Watch,Rs. 2999Rs. 6990(Rs. 3991 OFF)
24,pebble,"Cosmos Ultra 1.91"" BT Calling Smartwatch",Rs. 1599Rs. 7499(Rs. 5900 OFF)
25,Fire-Boltt,Aura BT Calling Smartwatch,Rs. 1999Rs. 11999(Rs. 10000 OFF)
26,NOISE,ColorFit Icon 2 Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
27,Fire-Boltt,Visionary TWS Smartwatch,Rs. 2499Rs. 18499(Rs. 16000 OFF)
28,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
29,Realme,TechLife Watch S100,Rs. 2499Rs. 3999(Rs. 1500 OFF)
30,NOISE,ColorFit Icon 2 Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
31,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1999Rs. 19999(Rs. 18000 OFF)
32,boAt,Storm Plus AMOLED Smart Watch,Rs. 1899Rs. 8999(Rs. 7100 OFF)
33,Fastrack,Z1 with HD Display Smartwatch,Rs. 1995Rs. 3995(Rs. 2000 OFF)
34,boAt,Lunar Fit Smart Watch,Rs. 2999Rs. 6990(Rs. 3991 OFF)
35,NOISE,ColorFit Pro 5 Smartwatch,Rs. 3999Rs. 8999(Rs. 5000 OFF)
36,Fire-Boltt,Sphere Rugged Smartwatch,Rs. 1899Rs. 19999(Rs. 18100 OFF)
37,boAt,Unisex Wave Genesis Smartwatch,Rs. 1899Rs. 6499(Rs. 4600 OFF)
38,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
39,Fire-Boltt,Avalanche Luxury Smart Watch,Rs. 2199Rs. 21000(Rs. 18801 OFF)
40,NOISE,ColorFit Pro 5 Smartwatch,Rs. 3999Rs. 8999(Rs. 5000 OFF)
41,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1799Rs. 17999(Rs. 16200 OFF)
42,NOISE,Evolve 3 Smartwatch,Rs. 2449Rs. 6999(Rs. 4550 OFF)
43,Fire-Boltt,Hurricane Smartwatch,Rs. 1899Rs. 8999(Rs. 7100 OFF)
44,boAt,Lunar Mirage Smartwatch,Rs. 1599Rs. 7999(Rs. 6400 OFF)
45,Timex,iConnect Gen+ Smart Watch,Rs. 2527Rs. 5495(54% OFF)
46,NOISE,ColorFit Pro 5 Smartwatch,Rs. 3999Rs. 8999(Rs. 5000 OFF)
47,Fire-Boltt,Crusader Amoled 1.43BT Calling,Rs. 1899Rs. 18999(Rs. 17100 OFF)
48,Cultsport,"Ace X Luxe 1.96"" Smart Watches",Rs. 3479Rs. 11999(71% OFF)
49,CMF by Nothing,Watch Pro,Rs. 3499Rs. 5999(Rs. 2500 OFF)